--Drop Table
--Drop Table Statements
DROP TABLE IF EXISTS MEMBER_WORKOUT_PLAN;
DROP TABLE IF EXISTS PAYMENT;
DROP TABLE IF EXISTS WORKOUT_PLAN;
DROP TABLE IF EXISTS MEMBER;
DROP TABLE IF EXISTS INSTRUCTOR;
DROP TABLE IF EXISTS MEMBERSHIP_TYPE;
DROP TABLE IF EXISTS MANAGER;

-- Managers Table
CREATE TABLE MANAGER (
    ManagerID INT PRIMARY KEY,
    FirstName VARCHAR(255) NOT NULL,
    LastName VARCHAR(255) NOT NULL,
    PhoneNumber VARCHAR(20)
);

-- Membership_Type Table
CREATE TABLE MEMBERSHIP_TYPE (
    TypeID INT PRIMARY KEY,
    Name VARCHAR(100) NOT NULL,
    Period INT NOT NULL,
    Amount DECIMAL(10,2) NOT NULL
);

-- Instructor Table
CREATE TABLE INSTRUCTOR (
    InstructorID INT PRIMARY KEY,
    FirstName VARCHAR(255) NOT NULL,
    LastName VARCHAR(255) NOT NULL,
    PhoneNumber VARCHAR(20),
    ManagerID INT NULL,
    CONSTRAINT fk_instr_mgr FOREIGN KEY (ManagerID)
        REFERENCES MANAGER(ManagerID) ON DELETE SET NULL
);

-- Member Table
CREATE TABLE MEMBER (
    MemberID INT PRIMARY KEY,
    FirstName VARCHAR(255) NOT NULL,
    LastName VARCHAR(255) NOT NULL,
    PhoneNumber VARCHAR(20),
    ManagerID INT NULL,
    TypeID INT NULL,
    CONSTRAINT fk_mem_mgr FOREIGN KEY (ManagerID)
        REFERENCES MANAGER(ManagerID) ON DELETE SET NULL,
    CONSTRAINT fk_mem_type FOREIGN KEY (TypeID)
        REFERENCES MEMBERSHIP_TYPE(TypeID) ON DELETE SET NULL
);

-- Workout Plans Table
CREATE TABLE WORKOUT_PLAN (
    PlanID INT PRIMARY KEY,
    WorkoutType VARCHAR(255) NOT NULL,
    Description VARCHAR(1000),
    WorkoutDate DATE NOT NULL,
    WorkoutTime DATE NULL,
    InstructorID INT NULL,
    CONSTRAINT fk_plan_instr FOREIGN KEY (InstructorID)
        REFERENCES INSTRUCTOR(InstructorID) ON DELETE SET NULL
);

-- Payment Table
CREATE TABLE PAYMENT (
    PaymentID INT PRIMARY KEY,
    PaymentDate DATE DEFAULT CURRENT_DATE,
    Amount DECIMAL(10,2) NOT NULL,
    MemberID INT NOT NULL,
    CONSTRAINT fk_pay_mem FOREIGN KEY (MemberID)
        REFERENCES MEMBER(MemberID) ON DELETE CASCADE
);

-- Member Workout Plan Table
CREATE TABLE MEMBER_WORKOUT_PLAN (
    MemberID INT NOT NULL,
    PlanID INT NOT NULL,
    PRIMARY KEY (MemberID, PlanID),
    CONSTRAINT fk_mwp_mem FOREIGN KEY (MemberID)
        REFERENCES MEMBER(MemberID) ON DELETE CASCADE,
    CONSTRAINT fk_mwp_plan FOREIGN KEY (PlanID)
        REFERENCES WORKOUT_PLAN(PlanID) ON DELETE CASCADE
);
