-- Relation query that show each member's full name along with their membership type and assigned manager.
SELECT 
    m.FirstName || ' ' || m.LastName AS Member_Name,
    mt.Name AS Membership_Type,
    mgr.FirstName || ' ' || mgr.LastName AS Manager_Name
FROM MEMBER m
JOIN MEMBERSHIP_TYPE mt ON m.TypeID = mt.TypeID
JOIN MANAGER mgr ON m.ManagerID = mgr.ManagerID
ORDER BY Member_Name;

-- Calculate the total revenue generated by each member.
SELECT 
    m.FirstName || ' ' || m.LastName AS Member_Name,
    SUM(p.Amount) AS Total_Paid
FROM MEMBER m
JOIN PAYMENT p ON m.MemberID = p.MemberID
GROUP BY m.FirstName, m.LastName
ORDER BY Total_Paid DESC;

-- Find all payments greater than $100 made in 2025
SELECT 
    PaymentID,
    PaymentDate,
    Amount,
    MemberID
FROM PAYMENT
WHERE Amount > 100
AND PaymentDate BETWEEN DATE '2025-01-01' AND DATE '2025-12-31'
ORDER BY PaymentDate;

